// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "../AuthMode";
import type { ExternalAuthReceipt } from "./ExternalAuthReceipt";

export type AuthObservation = { version: number, mode: AuthMode | null, accountId: string | null, principal: string | null, stateKnown: boolean, provider: ExternalAuthReceipt | null, };
