// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { AuthObservation } from "./AuthObservation";

export type GetAccountResponse = {account: Account | null, requiresOpenaiAuth: boolean, /**
 * Present only for the explicit cache-only read.
 */
authObservation?: AuthObservation | null};
