// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A token-free intent for a managed transition. The credential writer and the
 * authoritative auth operation intentionally live behind later server-side
 * admission stages; neither is represented on this wire surface.
 */
export type ManagedTransitionIntent = "adoptManagedAuth" | "adoptManagedLogout";
