// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedTransitionRefusalKind } from "./ManagedTransitionRefusalKind";

export type ManagedTransitionRefusal = { kind: ManagedTransitionRefusalKind, retryable: boolean, processInstanceId: string, transitionId: string, authRevision: bigint, transitionRevision: bigint, authFingerprint: string | null, };
