// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed, secret-safe reasons for a transition request to be refused.
 */
export type ManagedTransitionRefusalKind = "invalidRequest" | "processMismatch" | "staleAuthRevision" | "staleTransitionRevision" | "staleAuthFingerprint" | "concurrentTransition" | "completedReplay" | "transitionIdConflict" | "lateCancellation" | "authorizationNotAdmitted";
