// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedTransitionIntent } from "./ManagedTransitionIntent";
import type { ManagedTransitionPhase } from "./ManagedTransitionPhase";
import type { ManagedTransitionRefusalKind } from "./ManagedTransitionRefusalKind";

export type ManagedTransitionStatus = { processInstanceId: string, transitionId: string | null, intent: ManagedTransitionIntent | null, phase: ManagedTransitionPhase, retryable: boolean, authRevision: bigint, transitionRevision: bigint, priorAuthFingerprint: string | null, resultAuthFingerprint: string | null, refusal: ManagedTransitionRefusalKind | null, };
