// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selected user configuration layer that contributes to effective MCP
 * configuration.
 */
export type McpServerConfigIdentityLayer = {
/**
 * Normalized absolute path spelling from the accepted selected user
 * configuration snapshot. This deliberately does not resolve symlinks.
 */
filePath: string,
/**
 * Existing canonical layer version, in `sha256:...` form.
 */
version: string, };
