// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerConfigIdentityLayer } from "./McpServerConfigIdentityLayer";

/**
 * Identity of every selected user configuration layer that supplied effective
 * MCP configuration, ordered from base to highest-precedence profile.
 */
export type McpServerConfigIdentity = { layers: Array<McpServerConfigIdentityLayer>, };
