// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerConfigIdentity } from "./McpServerConfigIdentity";

/**
 * Paired MCP configuration identities for diagnostic comparison.
 *
 * `applied` is the selected user configuration layer accepted by the running
 * server's most recent successful startup or strict MCP reload. `current` is
 * read from the selected user configuration layer when this method runs.
 */
export type McpServerConfigIdentityResponse = { applied: McpServerConfigIdentity, current: McpServerConfigIdentity, };
