// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identity of the selected user configuration layer that supplied MCP
 * configuration.
 */
export type McpServerConfigIdentity = {
/**
 * Canonical absolute path of the selected user configuration layer.
 */
filePath: string,
/**
 * Existing canonical layer version, in `sha256:...` form.
 */
version: string, };
