// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for the server-owned clear-and-replace operation.
 */
export type ThreadClearParams = {
/**
 * The predecessor currently displayed by the requesting connection.
 */
threadId: string, };
