// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thread } from "./Thread";
import type { ThreadStartSource } from "./ThreadStartSource";

export type ThreadStartedNotification = { thread: Thread,
/**
 * The client-declared source for this start, when the source was supplied
 * on the corresponding `thread/start` request.
 */
sessionStartSource?: ThreadStartSource,
/**
 * The explicit predecessor of a `Clear` start. This is omitted for normal
 * new sessions and forks; resumes do not emit `thread/started`.
 */
clearPredecessorThreadId?: string, };
