// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-recorded succession, not proof of current interactive attachment.
 */
export type ThreadClearTransition = { transitionId: string, predecessorThreadId: string, successorThreadId: string, };
