// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAttachmentEntry } from "./ThreadAttachmentEntry";

/**
 * An atomic attachment-state transition. A zero count explicitly records a
 * removal; it is not encoded by omitting an entry.
 */
export type ThreadAttachmentChangedNotification = { generation: string, revision: bigint, changes: Array<ThreadAttachmentEntry>, };
