// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A server-owned count of trusted interactive clients attached to one exact
 * thread.
 *
 * This is attachment evidence only. It does not establish thread succession,
 * loaded state, or authority to transfer a clear transition.
 */
export type ThreadAttachmentEntry = { threadId: string, interactiveAttachmentCount: number, };
