// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadClearEndReason } from "./ThreadClearEndReason";

/**
 * Requester-scoped authoritative predecessor evidence for `thread/clear`.
 */
export type ThreadClearEndedNotification = { transitionId: string, predecessorThreadId: string, successorThreadId: string, reason: ThreadClearEndReason, };
