// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadClearRecoveryContext } from "./ThreadClearRecoveryContext";
import type { ThreadClearRecoveryDurability } from "./ThreadClearRecoveryDurability";

export type ThreadClearRecovery = { successorThreadId: string, context: ThreadClearRecoveryContext, durability: ThreadClearRecoveryDurability, };
