// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A server-owned count of trusted interactive clients attached to one exact
 * thread.
 *
 * This is subscription evidence only. It does not establish thread succession,
 * loaded state, or authority to transfer a clear transition.
 */
export type ThreadInteractiveSubscriptionEntry = { threadId: string,
/**
 * Distinct live thread-event subscriptions held by server-verified
 * interactive clients. Not evidence of human presence, focus or retention.
 */
interactiveSubscriptionCount: number, };
