// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Caller provenance, never an authoritative clear edge or a shutdown receipt.
 */
export type ThreadClearRecoveryContext = {
/**
 * Must match the recovery-read contract on this connection before creation.
 */
contractVersion: number,
/**
 * Null means genuinely no displayed predecessor, not an unavailable known ID.
 */
predecessorThreadId: string | null, };
