// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadClearRecovery } from "./ThreadClearRecovery";

export type ThreadClearRecoveryObservation = { "type": "support" } | { "type": "none" } | { "type": "pending", recovery: ThreadClearRecovery, } | { "type": "complete", recovery: ThreadClearRecovery, } | { "type": "failed", recovery: ThreadClearRecovery, };
