// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thread } from "./Thread";
import type { ThreadStartSource } from "./ThreadStartSource";

/**
 * Requester-scoped authoritative successor evidence for `thread/clear`.
 */
export type ThreadClearStartedNotification = { transitionId: string, predecessorThreadId: string, successorThread: Thread, startSource: ThreadStartSource, };
