// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";

/**
 * Fresh-session values supplied by the clearing client, not inherited live settings.
 */
export type ThreadClearModelSettings = {
/**
 * An unset model uses ordinary server model-default resolution.
 */
model: string | null,
/**
 * An unset effort replaces the predecessor's configured effort with no override.
 */
reasoningEffort: ReasoningEffort | null, };
