// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadInteractiveSubscriptionEntry } from "./ThreadInteractiveSubscriptionEntry";

/**
 * An atomic subscription-state transition. A zero count explicitly records a
 * removal; it is not encoded by omitting an entry.
 */
export type ThreadInteractiveSubscriptionChangedNotification = { generation: string, revision: bigint, changes: Array<ThreadInteractiveSubscriptionEntry>, };
