// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadClearModelSettings } from "./ThreadClearModelSettings";

/**
 * Parameters for the server-owned clear-and-replace operation.
 */
export type ThreadClearParams = {
/**
 * The predecessor currently displayed by the requesting connection.
 */
threadId: string,
/**
 * Required for successful clear: model settings resolved for a fresh session.
 * Missing or null input is decoded so the server can preserve authority checks,
 * then refused before creating a durable clear transition.
 */
modelSettings: ThreadClearModelSettings, };
